In [6]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('db.sqlite')  # Adjust path as needed
df = pd.read_sql("SELECT * FROM messages", conn)

df['created_at'] = pd.to_datetime(df['created_at']).dt.tz_localize(None).dt.normalize()
df['delivery_date'] = pd.to_datetime(df['delivery_date']).dt.tz_localize(None).dt.normalize()
df['delivered_at'] = pd.to_datetime(df['delivered_at'], errors='coerce').dt.date  # <-- Here

df['no._days_for_delivery'] = (df['delivery_date'] - df['created_at']).abs().dt.days

# select the columns you want only
df = df[['token', 'email', 'created_at', 'delivered_at', 'no._days_for_delivery']]
df.tail(5)

,token,email,created_at,delivered_at,no._days_for_delivery
8,26a94012,mandarioalexis@gmail.com,2025-06-21,NaT,0.0
9,3a7cc849,mandarioalexis@gmail.com,2025-06-22,2025-06-22,0.0
10,e054ee5b,mandarioalexis@gmail.com,2025-06-22,NaT,282.0
11,b191a699,mandarioalexis2@gmail.com,2025-06-22,2025-06-22,0.0
12,9164f8c9,mandarioalexis2@gmail.com,2025-06-22,NaT,1.0

In [7]:
from sqlalchemy import create_engine
import pandas as pd
import os

DATABASE_URL = os.environ.get('DATABASE_URL', 'sqlite:///db.sqlite')
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

engine = create_engine(DATABASE_URL)
df = pd.read_sql("SELECT * FROM messages", engine)

df['created_at'] = pd.to_datetime(df['created_at']).dt.tz_localize(None).dt.normalize()
df['delivery_date'] = pd.to_datetime(df['delivery_date']).dt.tz_localize(None).dt.normalize()
df['delivered_at'] = pd.to_datetime(df['delivered_at'], errors='coerce').dt.date

df['no._days_for_delivery'] = (df['delivery_date'] - df['created_at']).abs().dt.days
df = df[['token', 'email', 'created_at', 'delivered_at', 'no._days_for_delivery']]
df.tail(5)

,token,email,created_at,delivered_at,no._days_for_delivery
8,26a94012,mandarioalexis@gmail.com,2025-06-21,NaT,0.0
9,3a7cc849,mandarioalexis@gmail.com,2025-06-22,2025-06-22,0.0
10,e054ee5b,mandarioalexis@gmail.com,2025-06-22,NaT,282.0
11,b191a699,mandarioalexis2@gmail.com,2025-06-22,2025-06-22,0.0
12,9164f8c9,mandarioalexis2@gmail.com,2025-06-22,NaT,1.0